export const ENTRADA_INVALIDA = "Datos de entrada inválidos"
export const PERSONA_NO_ENCONTRADA_RFC = "No se encontró persona con el RFC proporcionado"
export const PERSONA_ENCONTRADA = "Persona encontrada exitosamente"
export const MENSAJE_ERROR_GENERICO = "Servicio no disponible. Inténtelo más tarde"
export const CREDENCIALES_INCORRECTAS = "Credenciales incorrectas"
export const CUENTA_INACTIVA = "La cuenta se encuentra inactiva"
